/* Daho Code klienti: kalitlar saqlanmaydi, faqat Railway backend bilan ishlaydi. */
const MODELS = { openai:['GPT-4o','GPT-4.1'], anthropic:['Claude 3.5 Sonnet','Claude 3.7 Sonnet'], gemini:['Gemini 2.0 Flash','Gemini 2.5 Pro'], openrouter:['Auto','Claude 3.7 Sonnet','GPT-4o','Gemini 2.5 Pro'] };
const CAPABILITIES = [{icon:'⌁',name:'Kod yozish',desc:'Fayllarni yaratish va tahrirlash',state:'Faol'},{icon:'⌘',name:'GitHub',desc:'Branch, commit va push',state:'Faol'},{icon:'⚡',name:'Railway deploy',desc:'Testdan so‘ng avtomatik deploy',state:'Faol'},{icon:'◉',name:'Self-improvement',desc:'Yangi capability yaratish',state:'Beta'},{icon:'▣',name:'Test runner',desc:'Kod sifatini tekshirish',state:'Faol'}];
const defaults={provider:'openai',model:'GPT-4o',endpoint:'',autoImprove:true,demoMode:true}; let settings={...defaults,...JSON.parse(localStorage.getItem('daho-settings')||'{}')}; let history=[];
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function log(text,type='info'){const box=$('#logs');if(box.querySelector('.empty-log'))box.innerHTML='';const row=document.createElement('div');row.className='log-row '+type;row.innerHTML=`<span>${type==='ok'?'✓':type==='error'?'!':'›'}</span><p>${esc(text)}</p><time>${new Date().toLocaleTimeString('uz-UZ',{hour:'2-digit',minute:'2-digit'})}</time>`;box.prepend(row)}
function updateModels(){const list=MODELS[settings.provider]||MODELS.openai;const select=$('#settingsModel');select.innerHTML=list.map(m=>`<option>${m}</option>`).join('');if(!list.includes(settings.model))settings.model=list[0];select.value=settings.model;$('#selectedModel').textContent=`${$('#providerSelect').selectedOptions[0]?.text||'OpenAI'} · ${settings.model}`}
function renderCapabilities(){ $('#capabilityList').innerHTML=CAPABILITIES.map(c=>`<div class="tool-card"><span class="tool-icon">${c.icon}</span><div><strong>${c.name}</strong><p>${c.desc}</p></div><span class="tool-state ${c.state==='Beta'?'beta':''}">${c.state}</span></div>`).join('') }
function save(){settings.provider=$('#providerSelect').value;settings.model=$('#settingsModel').value;settings.endpoint=$('#endpointInput').value.trim();settings.autoImprove=$('#autoImprove').checked;settings.demoMode=$('#demoMode').checked;localStorage.setItem('daho-settings',JSON.stringify(settings));updateModels();toast('Sozlamalar saqlandi');log('Sozlamalar yangilandi','ok')}
function addMessage(role,text){const item=document.createElement('div');item.className=`message ${role}`;item.innerHTML=`<span class="avatar">${role==='user'?'S':'✦'}</span><div class="bubble">${esc(text).replace(/\n/g,'<br>')}</div>`;$('#chatList').append(item);item.scrollIntoView({behavior:'smooth',block:'end'})}
async function send(){const input=$('#promptInput'), prompt=input.value.trim();if(!prompt)return;input.value='';addMessage('user',prompt);log(`Topshiriq qabul qilindi: ${prompt.slice(0,70)}`);$('#taskStatus').textContent='Rejalashtirilmoqda';$('#taskDetail').textContent='Agent capability registry va loyiha kontekstini tekshirmoqda';$('#progressBar').style.width='18%';$('#progressPercent').textContent='18%';
if(settings.endpoint&&!settings.demoMode){try{const res=await fetch(settings.endpoint.replace(/\/$/,'')+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:prompt,provider:settings.provider,model:settings.model,history})});if(!res.ok)throw Error('Backend javobi xato');const data=await res.json();const answer=data.reply??data.message??'Backend javob qaytarmadi.';history.push({role:'user',content:prompt},{role:'assistant',content:answer});addMessage('assistant',answer);log('Backend javobi olindi','ok');finish();return}catch(e){log('Backend ulanmagan: demo javob ishlatildi','error')}}
setTimeout(()=>{const answer=`Topshiriq tahlil qilindi. Men ${settings.model} modeli bilan ishlayapman.\n\nDemo rejimda: kerakli capability'larni tekshirdim. Backend ulanganda men branch yaratib, kodni test qilib, muvaffaqiyatli bo‘lsa GitHub push va Railway deploy jarayonini boshlayman.`;addMessage('assistant',answer);log('Capability registry tekshirildi','ok');log('Demo javob tayyorlandi');finish()},500)}
function finish(){$('#taskStatus').textContent='Tayyor';$('#taskDetail').textContent='Topshiriq bajarildi yoki keyingi agent qadami kutilmoqda';$('#progressBar').style.width='100%';$('#progressPercent').textContent='100%'}
function navigate(target){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===target));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.target===target))}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.target));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#promptInput').value=b.dataset.prompt;$('#promptInput').focus()});$('#sendBtn').onclick=send;$('#promptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('#providerSelect').onchange=()=>{settings.provider=$('#providerSelect').value;updateModels()};$('#settingsModel').onchange=e=>settings.model=e.target.value;$('#saveSettings').onclick=save;$('#clearLogs').onclick=()=>$('#logs').innerHTML='<div class="empty-log">Hozircha loglar yo‘q</div>';$('#refreshTools').onclick=()=>{renderCapabilities();toast('Registry yangilandi')};$('#modelBtn').onclick=()=>navigate('settings');
$('#providerSelect').value=settings.provider;$('#endpointInput').value=settings.endpoint;$('#autoImprove').checked=settings.autoImprove;$('#demoMode').checked=settings.demoMode;updateModels();renderCapabilities();
